version: "3.5"

secrets:
  API_TOKEN:
    file: ./docker/secrets/API_TOKEN

services:
  bot:
    image: akkeluukkonen/rubus:latest
    restart: always
    secrets:
      - API_TOKEN
    volumes:
      - rubus-data:/data

volumes:
  rubus-data:
